<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hng_product-color-chip_box__QcjDW produ_dbbfd2</name>
   <tag></tag>
   <elementGuidId>4d6b3f75-4550-4bd5-8f37-e9c28933469b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-color-chip_box__QcjDW.product-color-chip_hover__E_ee2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='color-509-1']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15fff80c-2dcb-4558-8089-59a7fac0a2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-color-chip_box__QcjDW product-color-chip_hover__E_ee2</value>
      <webElementGuid>0b4ef6f8-25e3-464e-8be4-78a5457cc2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color-509-1&quot;)/div[@class=&quot;product-color-chip_wrapper__R9FQA&quot;]/div[@class=&quot;product-color-chip_box__QcjDW product-color-chip_hover__E_ee2&quot;]</value>
      <webElementGuid>c8f60a35-ddbf-4d14-a807-374f58c913af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='color-509-1']/div/div</value>
      <webElementGuid>a336845a-8820-4509-b64d-b2760cc93d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/div[2]/div[2]/div/div</value>
      <webElementGuid>1ca36f31-6ebf-4113-9422-fdf45b169caa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
