<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ngi nhn_email</name>
   <tag></tag>
   <elementGuidId>4bb7e16b-4fc2-4fad-b1b7-b731d1e25aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2d7df1a-9329-4020-8251-34d98e6822b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> input__xl input--default pl-12 pr-4  w-full h-[52px] !pr-3 !pl-[42px] rounded-[4px] placeholder:text-yd-gray-100 border-yd-gray-50 truncate</value>
      <webElementGuid>ac55c9eb-13d9-4245-8a23-2b471b2a27af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ email (không bắt buộc)</value>
      <webElementGuid>933c52b5-07bf-4d13-967c-8f3ff48070e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64f4bb6b-8cf1-4fdf-80a6-b2e71138c244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4197bdc4-6ebe-477c-99dc-5090d27ceaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hook-form&quot;)/div[@class=&quot;flex flex-col px-4 xlg:pl-0 xlg:px-5 xlg:pr-0 bg-white mt-1 xlg:mt-0 xlg:pb-5&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;relative group inline-block hover:border-0  w-full&quot;]/input[@class=&quot;input__xl input--default pl-12 pr-4  w-full h-[52px] !pr-3 !pl-[42px] rounded-[4px] placeholder:text-yd-gray-100 border-yd-gray-50 truncate&quot;]</value>
      <webElementGuid>d45f4e6b-c6cc-4ac0-84c4-933d372939bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>1edd6e33-4786-4ab4-8e67-f520cb1f6365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hook-form']/div/div[2]/div[3]/div/input</value>
      <webElementGuid>aeb2a161-54da-45e1-a23f-47112c513c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8d09df96-789d-43fb-9022-67bf9c147769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Địa chỉ email (không bắt buộc)' and @type = 'text' and @name = 'email']</value>
      <webElementGuid>79a037e1-6807-4903-adc1-99ab2923354c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
