<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_X Yn Ph_address</name>
   <tag></tag>
   <elementGuidId>3e9309ae-4ea5-4082-9b76-ea2730ffe868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>690c26af-ad11-4d21-b0ab-015b77860632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> input__xl input--default pl-4 pr-4  w-full h-[52px] rounded-[4px] placeholder:text-yd-gray-100 border-yd-gray-50 truncate</value>
      <webElementGuid>f97e837e-c490-439e-b884-46f74c3aede5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập địa chỉ (ví dụ 90 Nguyễn Tuân) </value>
      <webElementGuid>a9aa81df-1953-4462-a800-bf3f2df9e14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>da71c1cf-72a5-40bc-aea1-cb20e37567ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b374e2ae-8d40-4429-8c45-2621899a107b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>84270261-2995-4b89-9926-b518ecad5d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hook-form&quot;)/div[@class=&quot;flex flex-col gap-4 px-4 pb-4 xlg:pl-0 xlg:pr-0 bg-white xlg:mt-0 xlg:pb-5&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;w-full relative&quot;]/div[@class=&quot;relative group inline-block hover:border-0  w-full&quot;]/input[@class=&quot;input__xl input--default pl-4 pr-4  w-full h-[52px] rounded-[4px] placeholder:text-yd-gray-100 border-yd-gray-50 truncate&quot;]</value>
      <webElementGuid>f47c3947-3471-4ab1-8f66-64ddc8713d15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address']</value>
      <webElementGuid>2f0f5810-9bdb-4e40-9f69-1e793bf6e760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hook-form']/div[2]/div[3]/div[3]/div/input</value>
      <webElementGuid>db4b2371-7726-4487-8e1c-edf46fd183bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/input</value>
      <webElementGuid>e47a3648-2f57-4418-bb73-d0218e9bb915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nhập địa chỉ (ví dụ 90 Nguyễn Tuân) ' and @type = 'text' and @name = 'address']</value>
      <webElementGuid>7e0c0ed9-d218-4eaa-a2d6-ca10da0ab46a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
