<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_o</name>
   <tag></tag>
   <elementGuidId>788e07c1-6ecc-4dc3-9c28-afa2919b0d72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.text-yd-button-text-2.px-0.py-2.w-full.truncate.text-left.mark-keyword.text-yd-button-text-2.text-yd-typo-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div/div/div/div[2]/div/div/div/div/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62996809-97cb-4c02-9be4-3e9a5391d4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-yd-button-text-2 px-0 py-2 w-full truncate text-left mark-keyword text-yd-button-text-2  text-yd-typo-title </value>
      <webElementGuid>56810207-4630-449b-9d7e-e7aea57d7dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>áo</value>
      <webElementGuid>45261a8c-0ee3-449d-b32a-067cfd5d8932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:rpi:&quot;)/div[@class=&quot;md:!container mx-auto flex justify-center items-center&quot;]/div[@class=&quot;flex flex-col gap-5 w-full pt-8 md:pt-10 md:pb-[4.5rem] md:w-[27.25rem]&quot;]/div[@class=&quot;px-9 md:px-0&quot;]/button[@class=&quot;text-yd-button-text-2 px-0 py-2 w-full truncate text-left mark-keyword text-yd-button-text-2  text-yd-typo-title&quot;]</value>
      <webElementGuid>dcc8ffea-1467-4f03-96e2-c6be2e2a4822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:rpi:']/div/div/div/button</value>
      <webElementGuid>34287720-f944-44d3-b390-54749db5bcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm kiếm nổi bật'])[1]/following::button[1]</value>
      <webElementGuid>30405bf3-5730-487f-b94a-0d923e7e9fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đóng'])[1]/following::button[1]</value>
      <webElementGuid>ecbc0f0e-6dba-486b-b711-639ba21fd89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='quần jean'])[1]/preceding::button[1]</value>
      <webElementGuid>1e383470-afdc-455d-8d0c-035fabb3cd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áo Khoác Gió Nữ 3C Plus Năng Động'])[2]/preceding::button[2]</value>
      <webElementGuid>a5b4e3af-d3e7-4c2b-b63b-ca824f0cf0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='áo']/parent::*</value>
      <webElementGuid>77e1a76b-5635-4bbc-9c09-8577c30fc7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button</value>
      <webElementGuid>73150af6-655e-4cb5-a463-e144b9a32efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'áo' or . = 'áo')]</value>
      <webElementGuid>d04512d5-3b12-4002-83ab-e0f619fbf028</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
