<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tt m Gi m_input__l input--default pl-_aa358f_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>04a0324b-6457-458d-8b25-fc14adfae9a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='á']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d65daa9-cc96-4b88-9058-9b7e3fb38881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> input__l input--default pl-12 pr-12  w-full bg-yd-grey-light-2 hover:bg-yd-grey-light-3 rounded-[1.25rem] text-yd-body-2 focus:border-0  !rounded-[1.25rem] bg-[#F2F5F8] w-full md:h-12 truncate</value>
      <webElementGuid>4cae88f2-a557-4723-97d9-16860f44a45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm kiếm</value>
      <webElementGuid>58698fcd-63e8-415c-ba78-eb2ffde328c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21595473-aacf-4288-b8de-dd279d68ed43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>á</value>
      <webElementGuid>32ae8db3-ad59-4c24-8098-48f5100ca5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:rsn:&quot;)/header[@class=&quot;h-[4.5rem] md:border-b border-yd-line-divider&quot;]/div[@class=&quot;h-full flex mx-auto justify-between items-center md:container px-4&quot;]/div[@class=&quot;relative w-full md:w-[436px]&quot;]/input[@class=&quot;input__l input--default pl-12 pr-12  w-full bg-yd-grey-light-2 hover:bg-yd-grey-light-3 rounded-[1.25rem] text-yd-body-2 focus:border-0  !rounded-[1.25rem] bg-[#F2F5F8] w-full md:h-12 truncate&quot;]</value>
      <webElementGuid>e92b3752-df6f-4729-a656-b26414b6620b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='á']</value>
      <webElementGuid>4044e35b-47c3-4577-a6e6-40a86088b962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:rsn:']/header/div/div/input</value>
      <webElementGuid>9d9e5f61-94b9-45a2-a744-c283e463e849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/input</value>
      <webElementGuid>a04b2ec1-13e8-4f71-9aa6-c3c5e31e86b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tìm kiếm' and @type = 'text']</value>
      <webElementGuid>ae54e103-222c-4b2a-a6d3-0554c7256543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
