<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tt m Gi m_input__l input--default pl-_aa358f_1_2</name>
   <tag></tag>
   <elementGuidId>f9dd51a8-72ee-4164-af5c-3ac183fa51b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='ao']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>716f55f5-9b29-494e-8f6a-0dab610776b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> input__l input--default pl-12 pr-12  w-full bg-yd-grey-light-2 hover:bg-yd-grey-light-3 rounded-[1.25rem] text-yd-body-2 focus:border-0  !rounded-[1.25rem] bg-[#F2F5F8] w-full md:h-12 truncate</value>
      <webElementGuid>d3993b1b-878f-49c3-a517-8650dfe1e4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm kiếm</value>
      <webElementGuid>7c1dc0ee-56a0-489e-a06f-b3a12d555096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2c764bf-e929-4aa5-9608-daa29f041a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ao</value>
      <webElementGuid>0cb36fcd-b6a6-4411-9b74-ecef051b29b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-:rsn:&quot;)/header[@class=&quot;h-[4.5rem] md:border-b border-yd-line-divider&quot;]/div[@class=&quot;h-full flex mx-auto justify-between items-center md:container px-4&quot;]/div[@class=&quot;relative w-full md:w-[436px]&quot;]/input[@class=&quot;input__l input--default pl-12 pr-12  w-full bg-yd-grey-light-2 hover:bg-yd-grey-light-3 rounded-[1.25rem] text-yd-body-2 focus:border-0  !rounded-[1.25rem] bg-[#F2F5F8] w-full md:h-12 truncate&quot;]</value>
      <webElementGuid>c86afcb1-6ce1-4c58-8d35-6914ef3f46d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='ao']</value>
      <webElementGuid>10d89efb-6275-470c-ab64-90043dd97be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:rsn:']/header/div/div/input</value>
      <webElementGuid>542b9d7c-d5a4-409e-8833-4a7727444b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/input</value>
      <webElementGuid>360d7dbd-123f-43d8-b75f-7a3490ac28e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tìm kiếm' and @type = 'text']</value>
      <webElementGuid>7b653273-10ce-4158-acfd-a8d1d736982c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
