<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_o Phao Nam Phi N Pro_object-cover w-ful_62e248</name>
   <tag></tag>
   <elementGuidId>50144abf-7d34-454f-9e0c-b88858b728bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Áo Phao Nữ Phối Nỉ Pro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f4725fca-e8ac-4c0a-9b5f-24a0cae37968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Áo Phao Nữ Phối Nỉ Pro</value>
      <webElementGuid>205247e9-7d73-4653-9af6-f0be0d482c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>675a052d-19ba-4234-aeeb-29a68a453a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>d0008824-99b1-4433-abac-2a45902eefc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>960</value>
      <webElementGuid>22cbba0d-8739-4a64-bd62-1974cc1fe05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>853df50f-673c-4955-a34d-47818b48caba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c8083a1-1fb4-48c7-84b4-7fd62f059bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-cover w-full product-card_image__9h71i</value>
      <webElementGuid>b988d978-2ae8-44a8-9cd1-dbf0cdfd11b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.yodycdn.com/fit-in/filters:format(webp)/products/ao-phao-nu-yody-PHN7004-HOG%20(5).jpg</value>
      <webElementGuid>c963093e-a353-4f67-aa4c-f553dd909581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_144c19&quot;]/div[2]/main[@class=&quot;relative&quot;]/div[1]/div[@class=&quot;space-y-4 lg:space-y-5 py-4 lg:py-5&quot;]/div[5]/div[1]/div[@class=&quot;overflow-hidden&quot;]/div[@class=&quot;md:container mx-auto&quot;]/div[@class=&quot;ProductSection_container-tab-wrapper__ShPhJ&quot;]/div[2]/div[@class=&quot;ProductSection_products-wrapper-tab__YV0aL&quot;]/a[2]/div[@class=&quot;relative overflow-hidden product-card_image_wrapper__tFqr_&quot;]/div[@class=&quot;relative&quot;]/img[@class=&quot;object-cover w-full product-card_image__9h71i&quot;]</value>
      <webElementGuid>909524a2-92eb-4ceb-838a-028a9470923c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Áo Phao Nữ Phối Nỉ Pro']</value>
      <webElementGuid>6c99346e-584e-4f32-a9c3-e63213511c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div[2]/div[2]/a[2]/div/div/img</value>
      <webElementGuid>26174dd1-652e-491e-a550-ff745f7236a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Áo Phao Nữ Phối Nỉ Pro' and @src = 'https://m.yodycdn.com/fit-in/filters:format(webp)/products/ao-phao-nu-yody-PHN7004-HOG%20(5).jpg']</value>
      <webElementGuid>8097fc79-8d8a-4593-b5fb-73d1c04334f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
